# Generated by Django 5.0.9 on 2024-09-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedb',
            name='number_of_connected_players',
            field=models.IntegerField(default=0),
        ),
    ]
