# Generated by Django 5.0.8 on 2024-08-24 16:48

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagGameDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_id', models.IntegerField()),
                ('player2_id', models.IntegerField()),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_remote', models.BooleanField(default=True)),
                ('player2_name', models.CharField(max_length=150, validators=[base.validators.CustomUsernameValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
