# Generated by Django 5.0.7 on 2024-09-02 04:44

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggamedb',
            name='player1_score',
        ),
        migrations.RemoveField(
            model_name='taggamedb',
            name='player2_score',
        ),
        migrations.AddField(
            model_name='taggamedb',
            name='player1_name',
            field=models.CharField(default='null', max_length=150, validators=[base.validators.CustomUsernameValidator()]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taggamedb',
            name='winner_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taggamedb',
            name='winner_name',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
