# Generated by Django 5.0.8 on 2024-09-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_taggamedb_player1_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggamedb',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taggamedb',
            name='winner_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
