# Generated by Django 5.0.7 on 2024-09-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_taggamedb_winner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggamedb',
            name='winner_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
