# Generated by Django 5.0.8 on 2024-08-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_onlinestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='from_user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='to_user_id',
            field=models.IntegerField(),
        ),
    ]
