# Generated by Django 4.0.10 on 2024-06-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuserprofile_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
