# Generated by Django 5.0.9 on 2024-10-21 16:03

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tournament_username',
            field=models.CharField(default='', max_length=10, validators=[base.validators.CustomUsernameValidator()]),
        ),
    ]
