# Generated by Django 4.0.10 on 2024-06-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_max_otp_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_max_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
