# Generated by Django 4.0.10 on 2024-06-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_is_authenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_authenticated',
            new_name='is_authentication_completed',
        ),
    ]
