# Generated by Django 4.0.10 on 2024-06-19 16:18

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required.4 characters or more and 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[base.validators.CustomUsernameValidator()], verbose_name='username'),
        ),
    ]
