# Generated by Django 4.0.10 on 2024-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, error_messages={'unique': 'A user with that email already exists.'}),
        ),
    ]
