# Generated by Django 4.0.10 on 2024-07-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logged_out',
            field=models.BooleanField(default=True),
        ),
    ]
