# Generated by Django 4.0.10 on 2024-07-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_user_is_logged_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
