# Generated by Django 4.0.10 on 2024-07-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_logged_out',
            field=models.BooleanField(default=False),
        ),
    ]
