# Generated by Django 5.0.8 on 2024-08-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_onlinestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineStatus',
        ),
    ]
