# Generated by Django 5.0.7 on 2024-08-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(default='1/8', max_length=50),
        ),
    ]
