# Generated by Django 5.0.7 on 2024-08-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_match_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(default=-1),
        ),
    ]
