# Generated by Django 5.0.8 on 2024-08-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_match_match_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(default='1/4', max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(default='upcoming', max_length=50),
        ),
    ]
