# Generated by Django 4.2.16 on 2024-11-01 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_left_paddle', models.PositiveSmallIntegerField()),
                ('y_right_paddle', models.PositiveSmallIntegerField()),
                ('x_ball', models.FloatField()),
                ('y_ball', models.FloatField()),
                ('vel_x_ball', models.FloatField()),
                ('vel_y_ball', models.FloatField()),
                ('pos_hit', models.FloatField(default=-1)),
                ('predict_pos_hit', models.FloatField(default=-1, null=True)),
                ('time', models.FloatField()),
                ('collision', models.BooleanField(default=False)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='base.turn')),
            ],
        ),
    ]
